26: Create applicant upload page with necessary components
HdM-LLM/frontend pull request #26
Opened 2023-11-20 09:55 UTC by MaxTyrchan

2023-11-20 16:27 UTC, ScottPalme requested changes

2023-11-20 16:27 UTC, ScottPalme commented on src/api/api.tsx
> +  addCoverLetter(cover_letter: File) {
This should be one request, which sends the cv together with the application letter. Something like:
`body: {
    cv: { ...},
    coverLetter: {...}
}`

2023-11-20 16:27 UTC, ScottPalme commented on src/api/api.tsx
> +  //Cover Letter
Please find a fitting name for the endpoint. Since we only need one endpoint for both files (see comment below)

2023-11-20 16:27 UTC, ScottPalme commented on src/pages/UploadPage.tsx
> +        <Button
Please delete one upload-button and only place one, maybe below both input fields.  For setting the state of both inputs maybe add another button per input or, if possible, set the state by clicking inside the input field.

2023-12-04 08:11 UTC, MaxTyrchan reviewed
Fixed all requested changes

2023-12-04 09:51 UTC, ScottPalme approved these changes

2023-12-04 09:51 UTC, merged