Implemented a first version for the vacancy page
HdM-LLM/frontend pull request #33
Opened 2023-12-04 21:36 UTC by NicoleSauer

- created vacancy page
- fixed some styling issues regarding the drawer
- made drawer a bit wider
- added green hover effect for elements
- switched SkillSync icon for something more fitting
- added navigation to the top left icon and text so it always navigates to the dashboard
- changed cursor style if hovering over something that is 'clickable'

Just as a side note: the drawer looks kinda small and the text looks tiny compared to the page I created. Maybe it is because of the 4k resolution. We´ll see, I guess 😁

---

EDIT 05.12.23:
- running the frontend on macOS, the font I chose seems to be missing. On Windows, it looks like this:
![image](https://github.com/HdM-LLM/frontend/assets/95630400/1df71f40-a623-4332-a3b5-90d0e9442e97)

2023-12-05 19:56 UTC, MaxTyrchan requested changes

2023-12-05 19:56 UTC, MaxTyrchan commented on src/components/VacancyCard.tsx
It seems that the vacancies "id's" from "mock-data"  are not working correctly because i receive the following error message:

<img width="212" alt="Bildschirmfoto 2023-12-05 um 20 43 52" src="https://github.com/HdM-LLM/frontend/assets/70903307/054e6696-b90c-46a9-9fd8-8baa11571fcb">

2023-12-05 19:56 UTC, MaxTyrchan commented on src/types/vacancy.ts
is "id" really a number?
i'm not sure if it will be a string or a native uuid or even a number...

2023-12-05 19:56 UTC, MaxTyrchan commented on src/components/Drawer.tsx
Somehow the underlaying "button" when clicking on the Logo in the top left has a width until the arrow i draw.
Maybe you can fix it to be only as wide as the Drawer.
<img width="763" alt="Bildschirmfoto 2023-12-05 um 20 52 23" src="https://github.com/HdM-LLM/frontend/assets/70903307/e5e97e0e-0068-4287-adcb-25819db6e4c3">

2023-12-06 09:31 UTC, NicoleSauer commented on src/components/VacancyCard.tsx
They are working but I forgot to move the `key` prop from the `<Grid item>` up to the `<NavLink>`. It is now fixed.

2023-12-06 09:43 UTC, NicoleSauer commented on src/components/Drawer.tsx
I added to both, icon and typography, the navigate function and the cursor switch when hovering over them. Now there is a small 'deadzone' between the icon and the typography, but it is way less noticable.

2023-12-06 20:32 UTC, merged