Created Loading Animation
HdM-LLM/frontend pull request #63
Opened 2024-01-03 13:29 UTC by MaxTyrchan

2024-01-03 13:31 UTC, MaxTyrchan commented
Please check if it's working accordingly because i'm unable to verify due to issues with the backend

2024-01-03 20:46 UTC, NicoleSauer requested changes
It works on my machine 😉

2024-01-03 20:46 UTC, NicoleSauer commented on src/pages/UploadPage.tsx
> +            console.log(response);
Please remove this console.log()

2024-01-03 20:46 UTC, NicoleSauer commented on src/pages/UploadPage.tsx
>        {success ? <Alert severity="success">🎉 Files sent successfully!</Alert> : <></>}
Not your fault, but could you do me a favour and change this to singular, since we are only sending one file? Thanks 😁

2024-01-04 10:21 UTC, NicoleSauer approved these changes

2024-01-04 10:22 UTC, merged